// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package stream_consumer

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
	"k8s.io/apimachinery/pkg/api/equality"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.ConsumerName, b.ko.Spec.ConsumerName) {
		delta.Add("Spec.ConsumerName", a.ko.Spec.ConsumerName, b.ko.Spec.ConsumerName)
	} else if a.ko.Spec.ConsumerName != nil && b.ko.Spec.ConsumerName != nil {
		if *a.ko.Spec.ConsumerName != *b.ko.Spec.ConsumerName {
			delta.Add("Spec.ConsumerName", a.ko.Spec.ConsumerName, b.ko.Spec.ConsumerName)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.StreamARN, b.ko.Spec.StreamARN) {
		delta.Add("Spec.StreamARN", a.ko.Spec.StreamARN, b.ko.Spec.StreamARN)
	} else if a.ko.Spec.StreamARN != nil && b.ko.Spec.StreamARN != nil {
		if *a.ko.Spec.StreamARN != *b.ko.Spec.StreamARN {
			delta.Add("Spec.StreamARN", a.ko.Spec.StreamARN, b.ko.Spec.StreamARN)
		}
	}
	if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.StreamRef, b.ko.Spec.StreamRef) {
		delta.Add("Spec.StreamRef", a.ko.Spec.StreamRef, b.ko.Spec.StreamRef)
	}

	return delta
}
