// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package stream

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}
	// DescribeStreamSummary returns an empty EncryptionType for unencrypted
	// streams, which the generated sdk.go maps to nil. Treat nil as NONE so
	// that a desired value of NONE does not produce a spurious delta against
	// an unencrypted stream and trigger an infinite reconcile loop.
	if a.ko.Spec.DesiredEncryptionType != nil && b.ko.Spec.DesiredEncryptionType == nil {
		none := "NONE"
		b.ko.Spec.DesiredEncryptionType = &none
	}

	// Before late-init runs, desired Spec fields are nil while latest (from
	// sdkFind mirroring) has the observed value. Suppress nil-vs-observed
	// deltas so that update hooks are not called with nil desired values.
	if a.ko.Spec.DesiredRetentionPeriodHours == nil && b.ko.Spec.DesiredRetentionPeriodHours != nil {
		a.ko.Spec.DesiredRetentionPeriodHours = b.ko.Spec.DesiredRetentionPeriodHours
	}
	if a.ko.Spec.DesiredEncryptionType == nil && b.ko.Spec.DesiredEncryptionType != nil {
		a.ko.Spec.DesiredEncryptionType = b.ko.Spec.DesiredEncryptionType
	}
	if a.ko.Spec.EncryptionKeyARN == nil && b.ko.Spec.EncryptionKeyARN != nil {
		a.ko.Spec.EncryptionKeyARN = b.ko.Spec.EncryptionKeyARN
	}

	if ackcompare.HasNilDifference(a.ko.Spec.DesiredEncryptionType, b.ko.Spec.DesiredEncryptionType) {
		delta.Add("Spec.DesiredEncryptionType", a.ko.Spec.DesiredEncryptionType, b.ko.Spec.DesiredEncryptionType)
	} else if a.ko.Spec.DesiredEncryptionType != nil && b.ko.Spec.DesiredEncryptionType != nil {
		if *a.ko.Spec.DesiredEncryptionType != *b.ko.Spec.DesiredEncryptionType {
			delta.Add("Spec.DesiredEncryptionType", a.ko.Spec.DesiredEncryptionType, b.ko.Spec.DesiredEncryptionType)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.DesiredRetentionPeriodHours, b.ko.Spec.DesiredRetentionPeriodHours) {
		delta.Add("Spec.DesiredRetentionPeriodHours", a.ko.Spec.DesiredRetentionPeriodHours, b.ko.Spec.DesiredRetentionPeriodHours)
	} else if a.ko.Spec.DesiredRetentionPeriodHours != nil && b.ko.Spec.DesiredRetentionPeriodHours != nil {
		if *a.ko.Spec.DesiredRetentionPeriodHours != *b.ko.Spec.DesiredRetentionPeriodHours {
			delta.Add("Spec.DesiredRetentionPeriodHours", a.ko.Spec.DesiredRetentionPeriodHours, b.ko.Spec.DesiredRetentionPeriodHours)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.EncryptionKeyARN, b.ko.Spec.EncryptionKeyARN) {
		delta.Add("Spec.EncryptionKeyARN", a.ko.Spec.EncryptionKeyARN, b.ko.Spec.EncryptionKeyARN)
	} else if a.ko.Spec.EncryptionKeyARN != nil && b.ko.Spec.EncryptionKeyARN != nil {
		if *a.ko.Spec.EncryptionKeyARN != *b.ko.Spec.EncryptionKeyARN {
			delta.Add("Spec.EncryptionKeyARN", a.ko.Spec.EncryptionKeyARN, b.ko.Spec.EncryptionKeyARN)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Name, b.ko.Spec.Name) {
		delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
	} else if a.ko.Spec.Name != nil && b.ko.Spec.Name != nil {
		if *a.ko.Spec.Name != *b.ko.Spec.Name {
			delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.ShardCount, b.ko.Spec.ShardCount) {
		delta.Add("Spec.ShardCount", a.ko.Spec.ShardCount, b.ko.Spec.ShardCount)
	} else if a.ko.Spec.ShardCount != nil && b.ko.Spec.ShardCount != nil {
		if *a.ko.Spec.ShardCount != *b.ko.Spec.ShardCount {
			delta.Add("Spec.ShardCount", a.ko.Spec.ShardCount, b.ko.Spec.ShardCount)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.StreamModeDetails, b.ko.Spec.StreamModeDetails) {
		delta.Add("Spec.StreamModeDetails", a.ko.Spec.StreamModeDetails, b.ko.Spec.StreamModeDetails)
	} else if a.ko.Spec.StreamModeDetails != nil && b.ko.Spec.StreamModeDetails != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.StreamModeDetails.StreamMode, b.ko.Spec.StreamModeDetails.StreamMode) {
			delta.Add("Spec.StreamModeDetails.StreamMode", a.ko.Spec.StreamModeDetails.StreamMode, b.ko.Spec.StreamModeDetails.StreamMode)
		} else if a.ko.Spec.StreamModeDetails.StreamMode != nil && b.ko.Spec.StreamModeDetails.StreamMode != nil {
			if *a.ko.Spec.StreamModeDetails.StreamMode != *b.ko.Spec.StreamModeDetails.StreamMode {
				delta.Add("Spec.StreamModeDetails.StreamMode", a.ko.Spec.StreamModeDetails.StreamMode, b.ko.Spec.StreamModeDetails.StreamMode)
			}
		}
	}
	desiredACKTags, _ := convertToOrderedACKTags(a.ko.Spec.Tags)
	latestACKTags, _ := convertToOrderedACKTags(b.ko.Spec.Tags)
	if !ackcompare.MapStringStringEqual(desiredACKTags, latestACKTags) {
		delta.Add("Spec.Tags", a.ko.Spec.Tags, b.ko.Spec.Tags)
	}

	return delta
}
