// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type ConsumerStatus string

const (
	ConsumerStatus_ACTIVE   ConsumerStatus = "ACTIVE"
	ConsumerStatus_CREATING ConsumerStatus = "CREATING"
	ConsumerStatus_DELETING ConsumerStatus = "DELETING"
)

type EncryptionType string

const (
	EncryptionType_KMS  EncryptionType = "KMS"
	EncryptionType_NONE EncryptionType = "NONE"
)

type MetricsName string

const (
	MetricsName_ALL                                MetricsName = "ALL"
	MetricsName_IncomingBytes                      MetricsName = "IncomingBytes"
	MetricsName_IncomingRecords                    MetricsName = "IncomingRecords"
	MetricsName_IteratorAgeMilliseconds            MetricsName = "IteratorAgeMilliseconds"
	MetricsName_OutgoingBytes                      MetricsName = "OutgoingBytes"
	MetricsName_OutgoingRecords                    MetricsName = "OutgoingRecords"
	MetricsName_ReadProvisionedThroughputExceeded  MetricsName = "ReadProvisionedThroughputExceeded"
	MetricsName_WriteProvisionedThroughputExceeded MetricsName = "WriteProvisionedThroughputExceeded"
)

type ScalingType string

const (
	ScalingType_UNIFORM_SCALING ScalingType = "UNIFORM_SCALING"
)

type ShardFilterType string

const (
	ShardFilterType_AFTER_SHARD_ID    ShardFilterType = "AFTER_SHARD_ID"
	ShardFilterType_AT_LATEST         ShardFilterType = "AT_LATEST"
	ShardFilterType_AT_TIMESTAMP      ShardFilterType = "AT_TIMESTAMP"
	ShardFilterType_AT_TRIM_HORIZON   ShardFilterType = "AT_TRIM_HORIZON"
	ShardFilterType_FROM_TIMESTAMP    ShardFilterType = "FROM_TIMESTAMP"
	ShardFilterType_FROM_TRIM_HORIZON ShardFilterType = "FROM_TRIM_HORIZON"
)

type ShardIteratorType string

const (
	ShardIteratorType_AFTER_SEQUENCE_NUMBER ShardIteratorType = "AFTER_SEQUENCE_NUMBER"
	ShardIteratorType_AT_SEQUENCE_NUMBER    ShardIteratorType = "AT_SEQUENCE_NUMBER"
	ShardIteratorType_AT_TIMESTAMP          ShardIteratorType = "AT_TIMESTAMP"
	ShardIteratorType_LATEST                ShardIteratorType = "LATEST"
	ShardIteratorType_TRIM_HORIZON          ShardIteratorType = "TRIM_HORIZON"
)

type StreamMode string

const (
	StreamMode_ON_DEMAND   StreamMode = "ON_DEMAND"
	StreamMode_PROVISIONED StreamMode = "PROVISIONED"
)

type StreamStatus_SDK string

const (
	StreamStatus_SDK_ACTIVE   StreamStatus_SDK = "ACTIVE"
	StreamStatus_SDK_CREATING StreamStatus_SDK = "CREATING"
	StreamStatus_SDK_DELETING StreamStatus_SDK = "DELETING"
	StreamStatus_SDK_UPDATING StreamStatus_SDK = "UPDATING"
)
