// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// StreamConsumerSpec defines the desired state of StreamConsumer.
type StreamConsumerSpec struct {

	// For a given Kinesis data stream, each consumer must have a unique name. However,
	// consumer names don't have to be unique across data streams.
	//
	// Regex Pattern: `^[a-zA-Z0-9_.-]+$`
	// +kubebuilder:validation:Required
	ConsumerName *string `json:"consumerName"`
	// The ARN of the Kinesis data stream that you want to register the consumer
	// with. For more info, see Amazon Resource Names (ARNs) and Amazon Web Services
	// Service Namespaces (https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html#arn-syntax-kinesis-streams).
	//
	// Regex Pattern: `^arn:aws.*:kinesis:.*:\d{12}:stream/\S+$`
	StreamARN *string                                  `json:"streamARN,omitempty"`
	StreamRef *ackv1alpha1.AWSResourceReferenceWrapper `json:"streamRef,omitempty"`
}

// StreamConsumerStatus defines the observed state of StreamConsumer
type StreamConsumerStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// When you register a consumer, Kinesis Data Streams generates an ARN for it.
	// You need this ARN to be able to call SubscribeToShard.
	//
	// If you delete a consumer and then create a new one with the same name, it
	// won't have the same ARN. That's because consumer ARNs contain the creation
	// timestamp. This is important to keep in mind if you have IAM policies that
	// reference consumer ARNs.
	//
	// Regex Pattern: `^(arn):aws.*:kinesis:.*:\d{12}:.*stream\/[a-zA-Z0-9_.-]+\/consumer\/[a-zA-Z0-9_.-]+:[0-9]+$`
	// +kubebuilder:validation:Optional
	ConsumerARN *string `json:"consumerARN,omitempty"`
	// +kubebuilder:validation:Optional
	ConsumerCreationTimestamp *metav1.Time `json:"consumerCreationTimestamp,omitempty"`
	// A consumer can't read data while in the CREATING or DELETING states.
	// +kubebuilder:validation:Optional
	ConsumerStatus *string `json:"consumerStatus,omitempty"`
}

// StreamConsumer is the Schema for the StreamConsumers API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type StreamConsumer struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              StreamConsumerSpec   `json:"spec,omitempty"`
	Status            StreamConsumerStatus `json:"status,omitempty"`
}

// StreamConsumerList contains a list of StreamConsumer
// +kubebuilder:object:root=true
type StreamConsumerList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []StreamConsumer `json:"items"`
}

func init() {
	SchemeBuilder.Register(&StreamConsumer{}, &StreamConsumerList{})
}
